### ISSUE TITLE
Organism.Detail: Organism Filter in 

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#180]
The general filter in Organism.Detail does not filter the correct number of entries
For example ‘coli’ gives only **12** Entries, but ‘coli’ in Organism Name gives **313** Entries

![image](https://user-images.githubusercontent.com/25675658/229963388-8d86f11f-75f1-4a0d-9bfe-cbd3009dfca9.png)
![image](https://user-images.githubusercontent.com/25675658/229963824-c705a995-9c4e-4fba-bc5a-0eb037db0314.png)

**Comment by Jo-Zh** [comment]
fixed by modify foreignkey fields in method def get_all_fields_q_object in apputil/utils.py
