### ISSUE TITLE
Organism Name Filter: more generic text filter and limited to OrgClass

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#182]
Can you make the filter in Organism Name to get all entries with 'coli', and not just the once which start with 'coli'  
Also limit the filter to entries of the OrgClass, to avoid editing the error message after saving of having the Wrong Class.

![image](https://user-images.githubusercontent.com/25675658/229964313-cfa7f052-ff13-44aa-a9e1-be8fe525ddbb.png)

**Comment by JZuegg** [comment]
One add-one: Should also have the existing organism name as default

**Comment by Jo-Zh** [comment]
solved in development branch.
