### ISSUE TITLE
Delete Message Change Icon

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#183]
Replace the Save Icon with the Delete Icon, in the Delete ... Popup
Change the message to include what entry is being deleted, like 'Organism FG_0002'

![image](https://user-images.githubusercontent.com/25675658/229964834-a166e04a-d6fe-41f4-96b2-b0b23a7929cc.png)

**Comment by Jo-Zh** [comment]
fixed by passing {{object}} to delete.html
