### ISSUE TITLE
Organism Culture Update missing and wrong fields

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#184]
1. Type, Source and Labware are not Updateable
2. Notes contains the Biologist field
3. Please remove Organism ID from the table, as it is fixed to the Organism entry.
4. Replace "update' 'cancel' with icons, like in the other update forms
5. Remove the text 'EDIT' from the header, like in the other views

![image](https://user-images.githubusercontent.com/25675658/229966395-f259ea35-02d6-4e5e-9ab5-1b1dfe32f741.png)

**Comment by Jo-Zh** [comment]
1-3 fixed by:
-  update forms.py adding form-group to update headerfields
-  add field.errors in views/def updateCulture(req, pk) and template culture_u.html 
4,5 fixed by:
-update culture_tr and culture_u.html
