### ISSUE TITLE
Organism Batch Update: Wrong fields

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#185]
1. The Batch Note contains the Biologist

![image](https://user-images.githubusercontent.com/25675658/229967161-48a6ca77-4fc5-49b4-b4af-f52e80b3c44b.png)

**Comment by Jo-Zh** [comment]
fixed by:
batch_c.html:  
{%for field in form.group_updatebatch%}
  <td>{{field}}</td>
  {%endfor%}

class Batchupdate_form(forms.ModelForm) in forms.py:
stock_level = HiddenSimpleArrayField(required=False)
def create_field_groups(self):
        self.group_updatebatch = [self[name] for name in ("batch_id", "stock_date", "stock_level", "qc_status", "qc_record", "batch_notes", "biologist" )]
