### ISSUE TITLE
Create Batch: Remove Micro Organism 

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#186]
1. Remove the updating/editing of the Organism Name/ID, as when creating a Batch in the OrganismView, the user should not be able to change the Organism Name for a Batch. ... or should be filled with the default from the Organism ... 
Error on saving when empty 
2. Make QC Records a re-sizeable Text form

![image](https://user-images.githubusercontent.com/25675658/229967455-3b70c561-a362-474c-8ca1-dfd6472d90ca.png)

**Comment by Jo-Zh** [comment]
fixed 1 Remove Micro Organism by:
- change createurls to createXXX/organism_id
- change modal_form.html, culture_c.html, batch_c.html
- change createBatch, createCulture view functions and forms.
