### ISSUE TITLE
Create Stock : #Vial Created missing

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#188]
1. The field for #Created is missing in the form
2. Remove Orgbatch_ID, as it is fixed to a given ID
3. Make Stock Note as res-sizable Textform
4. Can the form reordered (maybe with a separate CREATE_FIELDS)...
Stock Type, #Created, #Left
Stock Date, Stock Notes, Passage Notes
Freezer, Rack, Column, Slot
Biologist

![image](https://user-images.githubusercontent.com/25675658/229968714-cfa6b4fb-7fc7-49b8-af3f-802438891788.png)

**Comment by Jo-Zh** [comment]
fixed by
- change stock_createform
- model def save(...) method
- view def createStock(req, orgbatch_id)
