### ISSUE TITLE
Display of Dictionary 

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#189]
1. The display of Dictionary should be standardized, or at least limited to a few options which are applied in some consistent way
  DictValue .. for View
  DictValue | DictDescription  .. for Choices 
2. For Organism Culture display only DictValue in the View Table

![image](https://user-images.githubusercontent.com/25675658/229977635-01bd4e9e-014a-4e6b-be45-04eae9714b15.png)

**Comment by Jo-Zh** [comment]
fixed by:
in AuditModel def get_values():
...
if isinstance(obj, Model):
                        value_list.append(obj.pk)
--
