### ISSUE TITLE
Create OrgBatch: Allow empty Batch ID

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#199]
Hi,

The aim would be to allow Users to enter a custom Batch_ID, but also generate the next Batch_ID in case no cutsom Batch_ID is given.

Can you undisplay the form for model.batch_id, but maybe display a form for a seperate Custom Batch_ID (non model) field, which can be empty, and might be say 'Custom BatchID' ... 
The Organism_Batch.save() should be able to handle if no batch_id is given that it creates the next availble Batch_ID.

**Comment by Jo-Zh** [comment]
Added a info badge below the form field, provide option: fill the field or leave it blank...?
