### ISSUE TITLE
Update Stock: Missing values from Instance

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#200]
Hi,

1. Update Stock has no values for _N created_ and _Stock Date_ 

![image](https://user-images.githubusercontent.com/25675658/231082639-c8ae0d2b-2a52-4c13-8c3b-c8e38f8756c6.png)

**Comment by Jo-Zh** [comment]
solved by passing instance value to fields stock_date, n_created in initial method.
