### ISSUE TITLE
Drug Detail: Filter

### ISSUE THREAD

**Issue by JZuegg** [CO-ADD/adjCOADD#202]
1. Please remove the MOL contains
2. Add checkboxes for **Drug Type**
3. Add **Target** filter
4. Add **Class** filter
5. Add **Antimicro** filter

![image](https://user-images.githubusercontent.com/25675658/231088887-202dd9b1-8adb-4815-b3d5-ee51fad9c6e3.png)

**Comment by Jo-Zh** [comment]
fixed
